# Generated by Django 6.0.2 on 2026-02-25 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ACCESS_REQUEST', 'Access Request'), ('ACCESS_APPROVED', 'Access Approved'), ('ACCESS_REJECTED', 'Access Rejected'), ('ACCESS_REVOKED', 'Access Revoked'), ('EMERGENCY_ACCESS', 'Emergency Access Used'), ('ACCESS_EXPIRED', 'Access Expired'), ('DOCUMENT_SHARED', 'Document Shared'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
