# Generated by Django 6.0.2 on 2026-02-25 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('scope', models.JSONField(default=list, help_text='List of document types doctor can access')),
                ('reason', models.TextField()),
                ('patient_note', models.TextField(blank=True, help_text="Patient's note when approving/rejecting")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(choices=[('LIFE_THREATENING', 'Life-Threatening Condition'), ('UNCONSCIOUS', 'Patient Unconscious / Unable to Consent'), ('MASS_CASUALTY', 'Mass Casualty / Disaster'), ('CRITICAL_PROCEDURE', 'Critical Procedure Required'), ('OTHER', 'Other Emergency')], max_length=30)),
                ('reason_detail', models.TextField()),
                ('patient_admit_id', models.CharField(help_text='OPD/ER token or admit ID', max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_reviewed_by_admin', models.BooleanField(default=False)),
                ('is_flagged_misuse', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
    ]
