# Generated by Django 6.0.2 on 2026-02-25 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyaccess',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emergencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
