# Generated by Django 6.0.2 on 2026-02-25 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('REPORT', 'Lab Report'), ('SCAN', 'Scan / Imaging'), ('DISCHARGE', 'Discharge Summary'), ('VACCINATION', 'Vaccination Record'), ('OTHER', 'Other')], max_length=20)),
                ('event_type', models.CharField(choices=[('HOSPITAL_VISIT', 'Hospital Visit'), ('DIAGNOSIS', 'Diagnosis'), ('PROCEDURE', 'Procedure'), ('CHECKUP', 'Checkup'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('hospital_name', models.CharField(blank=True, max_length=300)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('document_date', models.DateField()),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False, help_text='Accessible in emergency break-glass')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
    ]
