# Generated by Django 6.0.2 on 2026-02-25 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DOCUMENT_VIEW', 'Viewed Document'), ('DOCUMENT_DOWNLOAD', 'Downloaded Document'), ('DOCUMENT_UPLOAD', 'Uploaded Document'), ('DOCUMENT_DELETE', 'Deleted Document'), ('ACCESS_REQUEST', 'Sent Access Request'), ('ACCESS_APPROVE', 'Approved Access'), ('ACCESS_REJECT', 'Rejected Access'), ('ACCESS_REVOKE', 'Revoked Access'), ('EMERGENCY_ACCESS', 'Emergency Break-Glass Access'), ('PROFILE_UPDATE', 'Updated Profile'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=30)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('document_title', models.CharField(blank=True, max_length=300)),
                ('is_emergency', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
